spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**

        - id: sale-service
          uri: lb://SALE-SERVICE
          predicates:
            - Path=/api/v1/sale/**, /api/v1/offer/**

        - id: user-management-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/user/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/v1/report/**

        - id: logging-service
          uri: lb://LOGGING-SERVICE
          predicates:
            - Path=/api/v1/logging/**
  application:
    name: gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://${EUREKA_HOST:localhost}:8761/eureka/
