spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/