spring:
  application:
    name: USER-MANAGEMENT-SERVICE
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:productmanagementsystem}
    username: postgres
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone : http://${EUREKA_HOST:localhost}:8761/eureka/

server:
  port: 8083
  servlet:
    context-path: /api/v1

logging:
  config: ${LOG4J2_CONFIG_FILE:../log4j2.xml}
  level:
    dev.faruk: TRACE
